[package]
name = "bis-store"
version = "0.1.0"
description = "Data storage for Book Information System"

repository.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
