name: SBOM on Release

on:
  push:
    tags:
      - '*'

permissions:
  actions: read
  contents: write
  
jobs:
  sbom:
    uses: ./.github/workflows/sbom.yml
    with:
      scan-target: docker
      image-tag: my-release:latest
      sbom-format: syft-json
      artifact-name: syft.sbom.json

  scan:
    uses: ./.github/workflows/scan.yml
    needs: sbom
    with: 
      sbom-artifact: syft.sbom.json

  attach-artifacts:
    name: Upload SARIF to Release
    needs: scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: Download SARIF
        uses: actions/download-artifact@v4
        with:
          name: sarif
          path: artifacts

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*
