
name: SBOM on Release

on:
  workflow_dispatch:
  
jobs:
  sbom:
    uses: ./.github/workflows/sbom.yml
    with:
      scan-target: docker
      image-tag: my-release:latest
      sbom-format: syft-json
      artifact-name: syft.sbom.json

  scan:
    uses: ./.github/workflows/scan.yml
    needs: sbom
    with: 
      sbom-file: syft.sbom.json
