
name: SBOM on Release

on:
  workflow_dispatch:
  
jobs:
  scan:
    uses: ./.github/workflows/sbom.yml
    with:
      scan-target: docker
      image-tag: my-release:latest
      sbom-format: syft-json
